
value:
  AccessKeyID: "******"
  AccessKeySecret: ""******""
  AppKey: ""******""
  AudioFile: "/smartaudio/audio/"
  RobotUrl: "http://openapi.tuling123.com/openapi/api/v2"
  RobotApiKey: ""******""
  RobotUserId: "123456"



logging:
  level:
    TimerConfig: info

server:
  tomcat:
    basedir: /smartaudio/tmp/


spring:
  servlet:
    multipart:
      max-file-size: 10MB
